const CHESS_GRID = [
  [
    { simbol: "R", posiblePosition: false, posibleId: "", id: "v6Zje", posiblePositions: [] },
    { simbol: "P", posiblePosition: false, posibleId: "", id: "bFP4K", posiblePositions: [] },
    { simbol: 0, posiblePosition: false, posibleId: "", id: "", posiblePositions: [] },
    { simbol: 0, posiblePosition: false, posibleId: "", id: "", posiblePositions: [] },
    { simbol: 0, posiblePosition: false, posibleId: "", id: "", posiblePositions: [] },
    { simbol: 0, posiblePosition: false, posibleId: "", id: "", posiblePositions: [] },
    { simbol: "p", posiblePosition: false, posibleId: "", id: "EXVU8", posiblePositions: [] },
    { simbol: "r", posiblePosition: false, posibleId: "", id: "gUYTd", posiblePositions: [] },
  ],
  [
    { simbol: "N", posiblePosition: false, posibleId: "", id: "TBWtm", posiblePositions: [] },
    { simbol: "P", posiblePosition: false, posibleId: "", id: "mezvg", posiblePositions: [] },
    { simbol: 0, posiblePosition: false, posibleId: "", id: "", posiblePositions: [] },
    { simbol: 0, posiblePosition: false, posibleId: "", id: "", posiblePositions: [] },
    { simbol: 0, posiblePosition: false, posibleId: "", id: "", posiblePositions: [] },
    { simbol: 0, posiblePosition: false, posibleId: "", id: "", posiblePositions: [] },
    { simbol: "p", posiblePosition: false, posibleId: "", id: "ezNwe", posiblePositions: [] },
    { simbol: "n", posiblePosition: false, posibleId: "", id: "WpIMn", posiblePositions: [] },
  ],
  [
    { simbol: "B", posiblePosition: false, posibleId: "", id: "X_E4K", posiblePositions: [] },
    { simbol: "P", posiblePosition: false, posibleId: "", id: "mPrb8", posiblePositions: [] },
    { simbol: 0, posiblePosition: false, posibleId: "", id: "", posiblePositions: [] },
    { simbol: 0, posiblePosition: false, posibleId: "", id: "", posiblePositions: [] },
    { simbol: 0, posiblePosition: false, posibleId: "", id: "", posiblePositions: [] },
    { simbol: 0, posiblePosition: false, posibleId: "", id: "", posiblePositions: [] },
    { simbol: "p", posiblePosition: false, posibleId: "", id: "xAxlS", posiblePositions: [] },
    { simbol: "b", posiblePosition: false, posibleId: "", id: "RJg5X", posiblePositions: [] },
  ],
  [
    { simbol: "Q", posiblePosition: false, posibleId: "", id: "Yf0Ty", posiblePositions: [] },
    { simbol: "P", posiblePosition: false, posibleId: "", id: "yTA7K", posiblePositions: [] },
    { simbol: 0, posiblePosition: false, posibleId: "", id: "", posiblePositions: [] },
    { simbol: 0, posiblePosition: false, posibleId: "", id: "", posiblePositions: [] },
    { simbol: 0, posiblePosition: false, posibleId: "", id: "", posiblePositions: [] },
    { simbol: 0, posiblePosition: false, posibleId: "", id: "", posiblePositions: [] },
    { simbol: "p", posiblePosition: false, posibleId: "", id: "Jsg5J", posiblePositions: [] },
    { simbol: "k", posiblePosition: false, posibleId: "", id: "01Om7", posiblePositions: [] },
  ],
  [
    { simbol: "K", posiblePosition: false, posibleId: "", id: "NYbgN", posiblePositions: [] },
    { simbol: "P", posiblePosition: false, posibleId: "", id: "F6VpU", posiblePositions: [] },
    { simbol: 0, posiblePosition: false, posibleId: "", id: "", posiblePositions: [] },
    { simbol: 0, posiblePosition: false, posibleId: "", id: "", posiblePositions: [] },
    { simbol: 0, posiblePosition: false, posibleId: "", id: "", posiblePositions: [] },
    { simbol: 0, posiblePosition: false, posibleId: "", id: "", posiblePositions: [] },
    { simbol: "p", posiblePosition: false, posibleId: "", id: "gX9-L", posiblePositions: [] },
    { simbol: "q", posiblePosition: false, posibleId: "", id: "3jQQa", posiblePositions: [] },
  ],
  [
    { simbol: "B", posiblePosition: false, posibleId: "", id: "b7v4V", posiblePositions: [] },
    { simbol: "P", posiblePosition: false, posibleId: "", id: "STohc", posiblePositions: [] },
    { simbol: 0, posiblePosition: false, posibleId: "", id: "", posiblePositions: [] },
    { simbol: 0, posiblePosition: false, posibleId: "", id: "", posiblePositions: [] },
    { simbol: 0, posiblePosition: false, posibleId: "", id: "", posiblePositions: [] },
    { simbol: 0, posiblePosition: false, posibleId: "", id: "", posiblePositions: [] },
    { simbol: "p", posiblePosition: false, posibleId: "", id: "gMYhg", posiblePositions: [] },
    { simbol: "b", posiblePosition: false, posibleId: "", id: "GhStW", posiblePositions: [] },
  ],
  [
    { simbol: "N", posiblePosition: false, posibleId: "", id: "tNWrL", posiblePositions: [] },
    { simbol: "P", posiblePosition: false, posibleId: "", id: "OCloz", posiblePositions: [] },
    { simbol: 0, posiblePosition: false, posibleId: "", id: "", posiblePositions: [] },
    { simbol: 0, posiblePosition: false, posibleId: "", id: "", posiblePositions: [] },
    { simbol: 0, posiblePosition: false, posibleId: "", id: "", posiblePositions: [] },
    { simbol: 0, posiblePosition: false, posibleId: "", id: "", posiblePositions: [] },
    { simbol: "p", posiblePosition: false, posibleId: "", id: "", posiblePositions: [] },
    { simbol: "n", posiblePosition: false, posibleId: "", id: "", posiblePositions: [] },
  ],
  [
    { simbol: "R", posiblePosition: false, posibleId: "", id: "hTM6j", posiblePositions: [] },
    { simbol: "P", posiblePosition: false, posibleId: "", id: "kT4cj", posiblePositions: [] },
    { simbol: 0, posiblePosition: false, posibleId: "", id: "", posiblePositions: [] },
    { simbol: 0, posiblePosition: false, posibleId: "", id: "", posiblePositions: [] },
    { simbol: 0, posiblePosition: false, posibleId: "", id: "", posiblePositions: [] },
    { simbol: 0, posiblePosition: false, posibleId: "", id: "", posiblePositions: [] },
    { simbol: "p", posiblePosition: false, posibleId: "", id: "8qpg4", posiblePositions: [] },
    { simbol: "r", posiblePosition: false, posibleId: "", id: "HAH_4", posiblePositions: [] },
  ],
];

export default CHESS_GRID;
